name: TS Test

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "vitest.config.ts"
      - "tsconfig.json"
      - "package*.json"
      - ".github/workflows/ts-test.yml"
  pull_request:
    paths:
      - "src/**"
      - "vitest.config.ts"
      - "tsconfig.json"
      - "package*.json"
      - ".github/workflows/ts-test.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - run: npm ci

      - name: Vitest
        run: npm test
